modLoader="javafml"
loaderVersion="${loader_range}"
issueTrackerURL="https://github.com/progwml6/Natura/issues"
license="Creative Commons 3"

[[mods]]
    modId="natura"
    version="${version}"
    displayName="Natura"
    authors="mDiyo, Slime Knights"
    description='''
Heyo, Redwood trees! Chop them all day long!
    '''
    displayURL="https://www.curseforge.com/minecraft/mc-mods/natura"
    
[[dependencies.natura]]
    modId="forge"
    mandatory=true
    versionRange="${forge_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.natura]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.natura]]
    modId="mantle"
    mandatory=true
    versionRange="${mantle_range}"
    ordering="NONE"
    side="BOTH"
