modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/progwml6/Natura/issues"
logoFile="logo.png"

[[mods]]
    modId="natura"
    version="${version}"
    displayName="Natura"
    authors="Progwml6, alexbegt"
    description='''
Heyo, Redwood trees! Chop them all day long!
    '''
    displayURL="http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294968-natura"
    [[dependencies.natura]]
        modId="forge"
        mandatory=true
        versionRange="[${forge_version},)"
        ordering="NONE"
        side="BOTH"
